name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  # NOTE: Here are some observations on 2023-02-19:
  #   - The inputs are passed to `pre`, `main`, and `post`.
  #   - `pre` will not execute when the action is local (./).
  #   - The environment variables are the same for `pre`, `main`, and `post`.
  #   - `pre`, `main`, and `post` are repeated for each action call
  # I don't see any value in `pre` or `post`.
  main: 'main.js'
